/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBifrostVToken__factory } from "./IBifrostVToken__factory";
export { ISLPx__factory } from "./ISLPx__factory";
