/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MockERC20 } from "./MockERC20";
export type { NeuroVault } from "./NeuroVault";
