/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NeuroVault {
  export type GoalViewStruct = {
    id: BigNumberish;
    text: string;
    status: BigNumberish;
  };

  export type GoalViewStructOutput = [
    id: bigint,
    text: string,
    status: bigint
  ] & { id: bigint; text: string; status: bigint };

  export type ProposalStruct = {
    id: BigNumberish;
    ipfsHash: string;
    actionType: BigNumberish;
    description: string;
    amount: BigNumberish;
    token: AddressLike;
    targetToken: AddressLike;
    confidence: BigNumberish;
    status: BigNumberish;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    snapshotTotalStaked: BigNumberish;
    createdAt: BigNumberish;
    votingDeadline: BigNumberish;
    outcome: string;
    proposer: AddressLike;
  };

  export type ProposalStructOutput = [
    id: bigint,
    ipfsHash: string,
    actionType: bigint,
    description: string,
    amount: bigint,
    token: string,
    targetToken: string,
    confidence: bigint,
    status: bigint,
    votesFor: bigint,
    votesAgainst: bigint,
    snapshotTotalStaked: bigint,
    createdAt: bigint,
    votingDeadline: bigint,
    outcome: string,
    proposer: string
  ] & {
    id: bigint;
    ipfsHash: string;
    actionType: bigint;
    description: string;
    amount: bigint;
    token: string;
    targetToken: string;
    confidence: bigint;
    status: bigint;
    votesFor: bigint;
    votesAgainst: bigint;
    snapshotTotalStaked: bigint;
    createdAt: bigint;
    votingDeadline: bigint;
    outcome: string;
    proposer: string;
  };

  export type ProposalViewStruct = {
    id: BigNumberish;
    status: BigNumberish;
    outcome: string;
  };

  export type ProposalViewStructOutput = [
    id: bigint,
    status: bigint,
    outcome: string
  ] & { id: bigint; status: bigint; outcome: string };
}

export interface NeuroVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APY_DENOMINATOR"
      | "EXECUTION_COOLDOWN"
      | "MAX_SPEND_DOT"
      | "MAX_SPEND_USDC"
      | "QUORUM_DENOMINATOR"
      | "QUORUM_NUMERATOR"
      | "addGoal"
      | "agentAddress"
      | "approvedTargets"
      | "autoFinalizeEnabled"
      | "bifrostDest"
      | "bifrostModule"
      | "currentApy"
      | "depositUsdc"
      | "dotToken"
      | "emergencyWithdraw"
      | "executedProposalCount"
      | "expireProposal"
      | "finalizeProposal"
      | "getActiveGoals"
      | "getProposal"
      | "getRecentProposals"
      | "getStakerInfo"
      | "getTreasuryState"
      | "goalCount"
      | "goals"
      | "hasReachedQuorum"
      | "hasVoted"
      | "hyperbridgeDispatch"
      | "lastExecutionTime"
      | "owner"
      | "proposalCount"
      | "proposals"
      | "propose"
      | "proposeWithDeadline"
      | "renounceOwnership"
      | "setAgentAddress"
      | "setApprovedTarget"
      | "setApy"
      | "setAutoFinalizeEnabled"
      | "setBifrostRouting"
      | "setHyperbridgeDispatch"
      | "setVotingWindow"
      | "stake"
      | "stakerCount"
      | "stakers"
      | "totalStaked"
      | "transferOwnership"
      | "unstake"
      | "updateGoalStatus"
      | "usdcToken"
      | "vote"
      | "votingWindow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAddressUpdated"
      | "ApprovedTargetUpdated"
      | "CrossChainStakeDispatched"
      | "GoalUpdated"
      | "HyperbridgeUpdated"
      | "NewDeposit"
      | "OwnershipTransferred"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalRejected"
      | "Staked"
      | "Unstaked"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APY_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTION_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SPEND_DOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SPEND_USDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_NUMERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addGoal", values: [string]): string;
  encodeFunctionData(
    functionFragment: "agentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvedTargets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoFinalizeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bifrostDest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bifrostModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentApy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositUsdc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dotToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executedProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expireProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveGoals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryState",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "goalCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "goals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "hasReachedQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hyperbridgeDispatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastExecutionTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propose",
    values: [
      string,
      BigNumberish,
      string,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeWithDeadline",
    values: [
      string,
      BigNumberish,
      string,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedTarget",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setApy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoFinalizeEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBifrostRouting",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHyperbridgeDispatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGoalStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "votingWindow",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APY_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTION_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SPEND_DOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SPEND_USDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_NUMERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addGoal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoFinalizeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bifrostDest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bifrostModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentApy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dotToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executedProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveGoals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goalCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "goals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasReachedQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hyperbridgeDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastExecutionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "propose", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeWithDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setApy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutoFinalizeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBifrostRouting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHyperbridgeDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGoalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingWindow",
    data: BytesLike
  ): Result;
}

export namespace AgentAddressUpdatedEvent {
  export type InputTuple = [oldAgent: AddressLike, newAgent: AddressLike];
  export type OutputTuple = [oldAgent: string, newAgent: string];
  export interface OutputObject {
    oldAgent: string;
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovedTargetUpdatedEvent {
  export type InputTuple = [target: AddressLike, approved: boolean];
  export type OutputTuple = [target: string, approved: boolean];
  export interface OutputObject {
    target: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainStakeDispatchedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    commitment: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    commitment: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    commitment: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalUpdatedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    text: string,
    status: BigNumberish
  ];
  export type OutputTuple = [goalId: bigint, text: string, status: bigint];
  export interface OutputObject {
    goalId: bigint;
    text: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HyperbridgeUpdatedEvent {
  export type InputTuple = [newDispatch: AddressLike];
  export type OutputTuple = [newDispatch: string];
  export interface OutputObject {
    newDispatch: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewDepositEvent {
  export type InputTuple = [
    depositor: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [depositor: string, token: string, amount: bigint];
  export interface OutputObject {
    depositor: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    ipfsHash: string,
    actionType: BigNumberish,
    confidence: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    ipfsHash: string,
    actionType: bigint,
    confidence: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    ipfsHash: string;
    actionType: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, outcome: string];
  export type OutputTuple = [proposalId: bigint, outcome: string];
  export interface OutputObject {
    proposalId: bigint;
    outcome: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRejectedEvent {
  export type InputTuple = [proposalId: BigNumberish, reason: string];
  export type OutputTuple = [proposalId: bigint, reason: string];
  export interface OutputObject {
    proposalId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    support: boolean,
    weight: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    support: boolean;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NeuroVault extends BaseContract {
  connect(runner?: ContractRunner | null): NeuroVault;
  waitForDeployment(): Promise<this>;

  interface: NeuroVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APY_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  EXECUTION_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_SPEND_DOT: TypedContractMethod<[], [bigint], "view">;

  MAX_SPEND_USDC: TypedContractMethod<[], [bigint], "view">;

  QUORUM_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  QUORUM_NUMERATOR: TypedContractMethod<[], [bigint], "view">;

  addGoal: TypedContractMethod<[text: string], [void], "nonpayable">;

  agentAddress: TypedContractMethod<[], [string], "view">;

  approvedTargets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  autoFinalizeEnabled: TypedContractMethod<[], [boolean], "view">;

  bifrostDest: TypedContractMethod<[], [string], "view">;

  bifrostModule: TypedContractMethod<[], [string], "view">;

  currentApy: TypedContractMethod<[], [bigint], "view">;

  depositUsdc: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  dotToken: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  executedProposalCount: TypedContractMethod<[], [bigint], "view">;

  expireProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveGoals: TypedContractMethod<
    [],
    [NeuroVault.GoalViewStructOutput[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [NeuroVault.ProposalStructOutput],
    "view"
  >;

  getRecentProposals: TypedContractMethod<
    [count: BigNumberish],
    [NeuroVault.ProposalViewStructOutput[]],
    "view"
  >;

  getStakerInfo: TypedContractMethod<
    [staker: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        usdcDeposited: bigint;
        votingPower: bigint;
      }
    ],
    "view"
  >;

  getTreasuryState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        dotBalance: bigint;
        usdcBalance: bigint;
        activeProposals: bigint;
        apy: bigint;
      }
    ],
    "view"
  >;

  goalCount: TypedContractMethod<[], [bigint], "view">;

  goals: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string, bigint] & { id: bigint; text: string; status: bigint }],
    "view"
  >;

  hasReachedQuorum: TypedContractMethod<
    [proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  hyperbridgeDispatch: TypedContractMethod<[], [string], "view">;

  lastExecutionTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        ipfsHash: string;
        actionType: bigint;
        description: string;
        amount: bigint;
        token: string;
        targetToken: string;
        confidence: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        snapshotTotalStaked: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        outcome: string;
        proposer: string;
      }
    ],
    "view"
  >;

  propose: TypedContractMethod<
    [
      ipfsHash: string,
      actionType: BigNumberish,
      description: string,
      amount: BigNumberish,
      token: AddressLike,
      targetToken: AddressLike,
      confidence: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  proposeWithDeadline: TypedContractMethod<
    [
      ipfsHash: string,
      actionType: BigNumberish,
      description: string,
      amount: BigNumberish,
      token: AddressLike,
      targetToken: AddressLike,
      confidence: BigNumberish,
      customDeadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentAddress: TypedContractMethod<
    [newAgent: AddressLike],
    [void],
    "nonpayable"
  >;

  setApprovedTarget: TypedContractMethod<
    [target: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setApy: TypedContractMethod<[apyBps: BigNumberish], [void], "nonpayable">;

  setAutoFinalizeEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setBifrostRouting: TypedContractMethod<
    [dest: BytesLike, module: BytesLike],
    [void],
    "nonpayable"
  >;

  setHyperbridgeDispatch: TypedContractMethod<
    [newDispatch: AddressLike],
    [void],
    "nonpayable"
  >;

  setVotingWindow: TypedContractMethod<
    [windowSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakerCount: TypedContractMethod<[], [bigint], "view">;

  stakers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        usdcDeposited: bigint;
        lastVotedProposal: bigint;
      }
    ],
    "view"
  >;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  updateGoalStatus: TypedContractMethod<
    [goalId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<
    [proposalId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  votingWindow: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APY_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXECUTION_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SPEND_DOT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SPEND_USDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_NUMERATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addGoal"
  ): TypedContractMethod<[text: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approvedTargets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoFinalizeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "bifrostDest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bifrostModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentApy"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositUsdc"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dotToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executedProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "expireProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveGoals"
  ): TypedContractMethod<[], [NeuroVault.GoalViewStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [NeuroVault.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentProposals"
  ): TypedContractMethod<
    [count: BigNumberish],
    [NeuroVault.ProposalViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakerInfo"
  ): TypedContractMethod<
    [staker: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        usdcDeposited: bigint;
        votingPower: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTreasuryState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        dotBalance: bigint;
        usdcBalance: bigint;
        activeProposals: bigint;
        apy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "goalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string, bigint] & { id: bigint; text: string; status: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReachedQuorum"
  ): TypedContractMethod<[proposalId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hyperbridgeDispatch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastExecutionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        ipfsHash: string;
        actionType: bigint;
        description: string;
        amount: bigint;
        token: string;
        targetToken: string;
        confidence: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        snapshotTotalStaked: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        outcome: string;
        proposer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propose"
  ): TypedContractMethod<
    [
      ipfsHash: string,
      actionType: BigNumberish,
      description: string,
      amount: BigNumberish,
      token: AddressLike,
      targetToken: AddressLike,
      confidence: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeWithDeadline"
  ): TypedContractMethod<
    [
      ipfsHash: string,
      actionType: BigNumberish,
      description: string,
      amount: BigNumberish,
      token: AddressLike,
      targetToken: AddressLike,
      confidence: BigNumberish,
      customDeadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentAddress"
  ): TypedContractMethod<[newAgent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setApprovedTarget"
  ): TypedContractMethod<
    [target: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApy"
  ): TypedContractMethod<[apyBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAutoFinalizeEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBifrostRouting"
  ): TypedContractMethod<
    [dest: BytesLike, module: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHyperbridgeDispatch"
  ): TypedContractMethod<[newDispatch: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVotingWindow"
  ): TypedContractMethod<[windowSeconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        usdcDeposited: bigint;
        lastVotedProposal: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGoalStatus"
  ): TypedContractMethod<
    [goalId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votingWindow"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AgentAddressUpdated"
  ): TypedContractEvent<
    AgentAddressUpdatedEvent.InputTuple,
    AgentAddressUpdatedEvent.OutputTuple,
    AgentAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ApprovedTargetUpdated"
  ): TypedContractEvent<
    ApprovedTargetUpdatedEvent.InputTuple,
    ApprovedTargetUpdatedEvent.OutputTuple,
    ApprovedTargetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainStakeDispatched"
  ): TypedContractEvent<
    CrossChainStakeDispatchedEvent.InputTuple,
    CrossChainStakeDispatchedEvent.OutputTuple,
    CrossChainStakeDispatchedEvent.OutputObject
  >;
  getEvent(
    key: "GoalUpdated"
  ): TypedContractEvent<
    GoalUpdatedEvent.InputTuple,
    GoalUpdatedEvent.OutputTuple,
    GoalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HyperbridgeUpdated"
  ): TypedContractEvent<
    HyperbridgeUpdatedEvent.InputTuple,
    HyperbridgeUpdatedEvent.OutputTuple,
    HyperbridgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NewDeposit"
  ): TypedContractEvent<
    NewDepositEvent.InputTuple,
    NewDepositEvent.OutputTuple,
    NewDepositEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRejected"
  ): TypedContractEvent<
    ProposalRejectedEvent.InputTuple,
    ProposalRejectedEvent.OutputTuple,
    ProposalRejectedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "AgentAddressUpdated(address,address)": TypedContractEvent<
      AgentAddressUpdatedEvent.InputTuple,
      AgentAddressUpdatedEvent.OutputTuple,
      AgentAddressUpdatedEvent.OutputObject
    >;
    AgentAddressUpdated: TypedContractEvent<
      AgentAddressUpdatedEvent.InputTuple,
      AgentAddressUpdatedEvent.OutputTuple,
      AgentAddressUpdatedEvent.OutputObject
    >;

    "ApprovedTargetUpdated(address,bool)": TypedContractEvent<
      ApprovedTargetUpdatedEvent.InputTuple,
      ApprovedTargetUpdatedEvent.OutputTuple,
      ApprovedTargetUpdatedEvent.OutputObject
    >;
    ApprovedTargetUpdated: TypedContractEvent<
      ApprovedTargetUpdatedEvent.InputTuple,
      ApprovedTargetUpdatedEvent.OutputTuple,
      ApprovedTargetUpdatedEvent.OutputObject
    >;

    "CrossChainStakeDispatched(uint256,bytes32,uint256)": TypedContractEvent<
      CrossChainStakeDispatchedEvent.InputTuple,
      CrossChainStakeDispatchedEvent.OutputTuple,
      CrossChainStakeDispatchedEvent.OutputObject
    >;
    CrossChainStakeDispatched: TypedContractEvent<
      CrossChainStakeDispatchedEvent.InputTuple,
      CrossChainStakeDispatchedEvent.OutputTuple,
      CrossChainStakeDispatchedEvent.OutputObject
    >;

    "GoalUpdated(uint256,string,uint8)": TypedContractEvent<
      GoalUpdatedEvent.InputTuple,
      GoalUpdatedEvent.OutputTuple,
      GoalUpdatedEvent.OutputObject
    >;
    GoalUpdated: TypedContractEvent<
      GoalUpdatedEvent.InputTuple,
      GoalUpdatedEvent.OutputTuple,
      GoalUpdatedEvent.OutputObject
    >;

    "HyperbridgeUpdated(address)": TypedContractEvent<
      HyperbridgeUpdatedEvent.InputTuple,
      HyperbridgeUpdatedEvent.OutputTuple,
      HyperbridgeUpdatedEvent.OutputObject
    >;
    HyperbridgeUpdated: TypedContractEvent<
      HyperbridgeUpdatedEvent.InputTuple,
      HyperbridgeUpdatedEvent.OutputTuple,
      HyperbridgeUpdatedEvent.OutputObject
    >;

    "NewDeposit(address,address,uint256)": TypedContractEvent<
      NewDepositEvent.InputTuple,
      NewDepositEvent.OutputTuple,
      NewDepositEvent.OutputObject
    >;
    NewDeposit: TypedContractEvent<
      NewDepositEvent.InputTuple,
      NewDepositEvent.OutputTuple,
      NewDepositEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalCreated(uint256,string,uint8,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256,string)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalRejected(uint256,string)": TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;
    ProposalRejected: TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
