/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIsmpModule,
  IIsmpModuleInterface,
} from "../../../../contracts/interfaces/IHyperbridge.sol/IIsmpModule";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "from",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct PostRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "onAccept",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "bytes[]",
            name: "values",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
        ],
        internalType: "struct GetResponse",
        name: "response",
        type: "tuple",
      },
    ],
    name: "onGetResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "source",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "from",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeoutTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct PostRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "onPostRequestTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIsmpModule__factory {
  static readonly abi = _abi;
  static createInterface(): IIsmpModuleInterface {
    return new Interface(_abi) as IIsmpModuleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIsmpModule {
    return new Contract(address, _abi, runner) as unknown as IIsmpModule;
  }
}
