/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIsmpDispatch,
  IIsmpDispatchInterface,
} from "../../../../contracts/interfaces/IHyperbridge.sol/IIsmpDispatch";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchGet",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "commitment",
            type: "bytes32",
          },
        ],
        internalType: "struct DispatchResponse",
        name: "response",
        type: "tuple",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPost",
        name: "request",
        type: "tuple",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "commitment",
            type: "bytes32",
          },
        ],
        internalType: "struct DispatchResponse",
        name: "response",
        type: "tuple",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "to",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchPost",
        name: "request",
        type: "tuple",
      },
    ],
    name: "quote",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "dest",
            type: "bytes",
          },
          {
            internalType: "uint64",
            name: "height",
            type: "uint64",
          },
          {
            internalType: "bytes[]",
            name: "keys",
            type: "bytes[]",
          },
          {
            internalType: "uint64",
            name: "timeout",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
        ],
        internalType: "struct DispatchGet",
        name: "request",
        type: "tuple",
      },
    ],
    name: "quote",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIsmpDispatch__factory {
  static readonly abi = _abi;
  static createInterface(): IIsmpDispatchInterface {
    return new Interface(_abi) as IIsmpDispatchInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIsmpDispatch {
    return new Contract(address, _abi, runner) as unknown as IIsmpDispatch;
  }
}
