/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBifrostSol from "./IBifrost.sol";
export type { iBifrostSol };
import type * as iHyperbridgeSol from "./IHyperbridge.sol";
export type { iHyperbridgeSol };
