/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type DispatchGetStruct = {
  dest: BytesLike;
  height: BigNumberish;
  keys: BytesLike[];
  timeout: BigNumberish;
  fee: BigNumberish;
  payer: AddressLike;
};

export type DispatchGetStructOutput = [
  dest: string,
  height: bigint,
  keys: string[],
  timeout: bigint,
  fee: bigint,
  payer: string
] & {
  dest: string;
  height: bigint;
  keys: string[];
  timeout: bigint;
  fee: bigint;
  payer: string;
};

export type DispatchResponseStruct = { commitment: BytesLike };

export type DispatchResponseStructOutput = [commitment: string] & {
  commitment: string;
};

export type DispatchPostStruct = {
  dest: BytesLike;
  to: BytesLike;
  body: BytesLike;
  timeout: BigNumberish;
  fee: BigNumberish;
  payer: AddressLike;
};

export type DispatchPostStructOutput = [
  dest: string,
  to: string,
  body: string,
  timeout: bigint,
  fee: bigint,
  payer: string
] & {
  dest: string;
  to: string;
  body: string;
  timeout: bigint;
  fee: bigint;
  payer: string;
};

export interface IIsmpDispatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dispatch((bytes,uint64,bytes[],uint64,uint256,address))"
      | "dispatch((bytes,bytes,bytes,uint64,uint256,address))"
      | "quote((bytes,bytes,bytes,uint64,uint256,address))"
      | "quote((bytes,uint64,bytes[],uint64,uint256,address))"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dispatch((bytes,uint64,bytes[],uint64,uint256,address))",
    values: [DispatchGetStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch((bytes,bytes,bytes,uint64,uint256,address))",
    values: [DispatchPostStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "quote((bytes,bytes,bytes,uint64,uint256,address))",
    values: [DispatchPostStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "quote((bytes,uint64,bytes[],uint64,uint256,address))",
    values: [DispatchGetStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "dispatch((bytes,uint64,bytes[],uint64,uint256,address))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatch((bytes,bytes,bytes,uint64,uint256,address))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quote((bytes,bytes,bytes,uint64,uint256,address))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quote((bytes,uint64,bytes[],uint64,uint256,address))",
    data: BytesLike
  ): Result;
}

export interface IIsmpDispatch extends BaseContract {
  connect(runner?: ContractRunner | null): IIsmpDispatch;
  waitForDeployment(): Promise<this>;

  interface: IIsmpDispatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "dispatch((bytes,uint64,bytes[],uint64,uint256,address))": TypedContractMethod<
    [request: DispatchGetStruct],
    [DispatchResponseStructOutput],
    "payable"
  >;

  "dispatch((bytes,bytes,bytes,uint64,uint256,address))": TypedContractMethod<
    [request: DispatchPostStruct],
    [DispatchResponseStructOutput],
    "payable"
  >;

  "quote((bytes,bytes,bytes,uint64,uint256,address))": TypedContractMethod<
    [request: DispatchPostStruct],
    [bigint],
    "view"
  >;

  "quote((bytes,uint64,bytes[],uint64,uint256,address))": TypedContractMethod<
    [request: DispatchGetStruct],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dispatch((bytes,uint64,bytes[],uint64,uint256,address))"
  ): TypedContractMethod<
    [request: DispatchGetStruct],
    [DispatchResponseStructOutput],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispatch((bytes,bytes,bytes,uint64,uint256,address))"
  ): TypedContractMethod<
    [request: DispatchPostStruct],
    [DispatchResponseStructOutput],
    "payable"
  >;
  getFunction(
    nameOrSignature: "quote((bytes,bytes,bytes,uint64,uint256,address))"
  ): TypedContractMethod<[request: DispatchPostStruct], [bigint], "view">;
  getFunction(
    nameOrSignature: "quote((bytes,uint64,bytes[],uint64,uint256,address))"
  ): TypedContractMethod<[request: DispatchGetStruct], [bigint], "view">;

  filters: {};
}
