/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type PostRequestStruct = {
  source: BytesLike;
  dest: BytesLike;
  nonce: BigNumberish;
  from: BytesLike;
  to: BytesLike;
  timeoutTimestamp: BigNumberish;
  body: BytesLike;
};

export type PostRequestStructOutput = [
  source: string,
  dest: string,
  nonce: bigint,
  from: string,
  to: string,
  timeoutTimestamp: bigint,
  body: string
] & {
  source: string;
  dest: string;
  nonce: bigint;
  from: string;
  to: string;
  timeoutTimestamp: bigint;
  body: string;
};

export type GetResponseStruct = {
  source: BytesLike;
  dest: BytesLike;
  nonce: BigNumberish;
  height: BigNumberish;
  keys: BytesLike[];
  values: BytesLike[];
  timeoutTimestamp: BigNumberish;
};

export type GetResponseStructOutput = [
  source: string,
  dest: string,
  nonce: bigint,
  height: bigint,
  keys: string[],
  values: string[],
  timeoutTimestamp: bigint
] & {
  source: string;
  dest: string;
  nonce: bigint;
  height: bigint;
  keys: string[];
  values: string[];
  timeoutTimestamp: bigint;
};

export interface IIsmpModuleInterface extends Interface {
  getFunction(
    nameOrSignature: "onAccept" | "onGetResponse" | "onPostRequestTimeout"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "onAccept",
    values: [PostRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "onGetResponse",
    values: [GetResponseStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "onPostRequestTimeout",
    values: [PostRequestStruct]
  ): string;

  decodeFunctionResult(functionFragment: "onAccept", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onGetResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onPostRequestTimeout",
    data: BytesLike
  ): Result;
}

export interface IIsmpModule extends BaseContract {
  connect(runner?: ContractRunner | null): IIsmpModule;
  waitForDeployment(): Promise<this>;

  interface: IIsmpModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  onAccept: TypedContractMethod<
    [request: PostRequestStruct],
    [void],
    "nonpayable"
  >;

  onGetResponse: TypedContractMethod<
    [response: GetResponseStruct],
    [void],
    "nonpayable"
  >;

  onPostRequestTimeout: TypedContractMethod<
    [request: PostRequestStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "onAccept"
  ): TypedContractMethod<[request: PostRequestStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onGetResponse"
  ): TypedContractMethod<[response: GetResponseStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onPostRequestTimeout"
  ): TypedContractMethod<[request: PostRequestStruct], [void], "nonpayable">;

  filters: {};
}
